# -*- coding: utf-8 -*-
"""Nutrtionlabel_draft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Fbk1Yz-l1cJbyOHyPHyQKO8587Nvr1z
"""

import easyocr
import cv2

img = cv2.imread('/content/nutritionlabel.png')
img1 = cv2.imread('/content/nutritionlabel1.png')
reader = easyocr.Reader(['en'])

results = reader.readtext(img)
results1 = reader.readtext(img1)

#for element in results:
  #print(element[1])

Ingredients = False

for element in results:
  if element[2] > 0:

    if ":" in element[1]:
      Ingredients = True
    if Ingredients:
      if "," in element[1]:
        split = element[1].split(",")
        for word in split:
          if word != "":
            print(word)
      else:
        print(element[1])
        #print(element[2])

results = results1

Ingredients = False

for element in results:
  if element[2] > 0:

    if "INGRE" in element[1]:
      Ingredients = True
    if Ingredients:
      if "," in element[1]:
        split = element[1].split(",")
        for word in split:
          if word != "":
            print(word)
      else:
        print(element[1])
        #print(element[2])

